### PR TITLE
Branch timezone fix

### LINKED ISSUE #202: Timezone class is displayed incorrectly
1. GMT-0 is displayed as GMT-0. Should either disallow GMT-0 or autoformat it to GMT+0, since that's the timezone standard

2.  GMT+00 shows up as GMT+00 -> standardize the number of digits we display

### PR DESCRIPTION
**Pull request by tankangliang**
## Description

The `value` field in `Timezone` is now changed to hold an integer which will prevent strings like "GMT+00" from being kept in the system and to disambiguate "GMT+0" and "GMT-0" as they will be standardized to "GMT+0".

Fixes #202 

## Testing

Tested with "GMT+0", "GMT+00", "GMT-0", "GMT-00" which have all been added to the test cases.

## Remarks

Also added hashCode() tests to most of the classes in package `model`.

### CODE REVIEW

File: src/main/java/seedu/address/model/client/Timezone.java [hunk 1]
```diff
@@ -31,7 +31,7 @@
     private static final Pattern TIMEZONE_FORMAT = Pattern.compile(VALIDATION_REGEX);
 
 
-    public final String value;
+    public final int value;
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/client/Timezone.java]: Can change this to offset or offsetValue?

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 2]
```diff
@@ -42,6 +46,7 @@
 
     private final TagNoteMap tagNoteMap;
 
+
```
Comment (qwoprocks) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java]: why was this newline added lmao

Comment (qwoprocks) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java]: extra newline

**Review by qwoprocks — APPROVED** [review]
Other than the 2 small issues, LGTM
