### PR TITLE
Fixes for dry run bugs

### LINKED ISSUE #228: Increase test coverage for storage package

### LINKED ISSUE #280: [PE-D] IndexOutOfBoundsException after finding a client when the display panel is already showing another client
Steps to replicate (using the default data on initial application load):
```
client view 5
client find alex
```

Full log:
```
INFO: =============================[ Initializing TBM ]=============================
Oct 30, 2020 4:15:51 PM seedu.address.MainApp start
INFO: Starting TbmManager V1.2.1ea
Oct 30, 2020 4:15:51 PM seedu.address.ui.UiManager start
INFO: Starting UI...
Oct 30, 2020 4:15:59 PM seedu.address.logic.LogicManager execute
INFO: ----------------[USER COMMAND][client view 5]
Oct 30, 2020 4:15:59 PM seedu.address.logic.parser.MainParser parseCommand
INFO: Command Type: client Rest of command:  view 5
Oct 30, 2020 4:15:59 PM seedu.address.logic.parser.MainParser parseClientCommands
INFO: Command Type: view Rest of command:  5
Oct 30, 2020 4:15:59 PM seedu.address.model.widget.WidgetModelManager setWidgetClient
INFO: Setting client of widget to: Irfan Ibrahim
Oct 30, 2020 4:15:59 PM seedu.address.ui.MainWindow executeCommand
INFO: Result: Viewing client: Irfan Ibrahim
Oct 30, 2020 4:15:59 PM seedu.address.ui.MainWindow executeCommand
INFO: Widget View Option: CLIENT
Oct 30, 2020 4:15:59 PM seedu.address.ui.MainWindow executeCommand
INFO: Toggling client view
Oct 30, 2020 4:15:59 PM seedu.address.model.widget.WidgetModelManager getWidgetClient
INFO: Retrieving client of widget: Irfan Ibrahim
Oct 30, 2020 4:15:59 PM seedu.address.ui.MainWindow executeCommand
INFO: Irfan Ibrahim
Oct 30, 2020 4:15:59 PM seedu.address.model.widget.WidgetModelManager getWidgetClient
INFO: Retrieving client of widget: Irfan Ibrahim
Oct 30, 2020 4:16:02 PM seedu.address.logic.LogicManager execute
INFO: ----------------[USER COMMAND][client find alex]
Oct 30, 2020 4:16:02 PM seedu.address.logic.parser.MainParser parseCommand
INFO: Command Type: client Rest of command:  find alex
Oct 30, 2020 4:16:02 PM seedu.address.logic.parser.MainParser parseClientCommands
INFO: Command Type: find Rest of command:  alex
Exception in thread "JavaFX Application Thread" java.lang.IndexOutOfBoundsException
        at javafx.collections.transformation.SortedList.get(SortedList.java:168)
        at seedu.address.ui.WidgetViewBox.lambda$new$0(WidgetViewBox.java:60)
        at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.transformation.SortedList.sourceChanged(SortedList.java:114)
        at javafx.collections.transformation.TransformationList.lambda$getListener$0(TransformationList.java:106)
        at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
        at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
        at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
        at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
        at javafx.collections.transformation.FilteredList.refilter(FilteredList.java:338)
        at javafx.collections.transformation.FilteredList.access$000(FilteredList.java:50)
        at javafx.collections.transformation.FilteredList$1.invalidated(FilteredList.java:102)
        at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
        at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:147)
        at javafx.collections.transformation.FilteredList.setPredicate(FilteredList.java:125)
        at seedu.address.model.ModelManager.updateFilteredClientList(ModelManager.java:253)
        at seedu.address.logic.commands.ClientFindCommand.execute(ClientFindCommand.java:37)
        at seedu.address.logic.LogicManager.execute(LogicManager.java:51)
        at seedu.address.ui.MainWindow.executeCommand(MainWindow.java:185)
        at seedu.address.ui.CommandBox.handleCommandEntered(CommandBox.java:40)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.sun.javafx.reflect.Trampoline.invoke(MethodUtil.java:76)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at com.sun.javafx.reflect.MethodUtil.invoke(MethodUtil.java:273)
        at com.sun.javafx.fxml.MethodHelper.invoke(MethodHelper.java:83)
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1784)
        at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1670)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8879)
        at com.sun.javafx.scene.control.behavior.TextFieldBehavior.fire(TextFieldBehavior.java:184)
        at com.sun.javafx.scene.control.behavior.TextInputControlBehavior.lambda$keyMapping$62(TextInputControlBehavior.java:330)
        at com.sun.javafx.scene.control.inputmap.InputMap.handle(InputMap.java:274)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$KeyHandler.process(Scene.java:4058)
        at javafx.scene.Scene$KeyHandler.access$1500(Scene.java:4004)
        at javafx.scene.Scene.processKeyEvent(Scene.java:2121)
        at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2595)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
        at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
        at com.sun.glass.ui.View.notifyKey(View.java:971)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ianyong/ped#1

### LINKED ISSUE #288: [PE-D] Documentation on tags could be clearer
No details provided.

In the format, `client note add CLIENT_INDEX nt/NOTE_STRING [t/TAG]...` was written.
However, in the 3rd command, `client note add 4 t/meeting nt/need to slowly convince him to sign the contract` was written.

I feel that for sake of consistency, either the `[t/TAG]...` in the format should be placed before `nt/` or the `t/meeting` in the 3rd command could be placed after `nt/`. 

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: geoboom/ped#2

### LINKED ISSUE #291: [PE-D] Clear command does not clear the side panel of client information
# Steps to reproduce

Run `client view` on a valid client and then `clear` command.

# Expected

Both the left and right panels are cleared.

# Actual

Only the right panel is cleared.

I feel that the clear command should clear both panels for consistency sake.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: geoboom/ped#5

### LINKED ISSUE #292: [PE-D] Clear command feedback contains "Address book"
Quite self-explanatory - I think you need to check your codebase again to remove all traces of address book.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: geoboom/ped#6

### PR DESCRIPTION
**Pull request by tankangliang**
## Description

PR fixes the following issues.

Fixes #292 
Fixes #291 
Fixes #288 
Fixes #280 
Fixes #228 

## Testing

Run the following with the default sample TBM data:

1. `client view 5`
1. `client find alex`

At this point, no `IndexOutOfBoundsException` should be thrown. <- Check the logs for this as the program does not actually terminate even with this exception.

3. `client view 1`
4. `clear`

The result display should no longer show `Address book`, also, the left panel showing the client should also be cleared as well.

## Remarks

For issue #282, the default `ZoneOffset` class we are using does not support floats for offset hours so it is left unresolved for now.

### CODE REVIEW

File: src/main/java/seedu/address/ui/WidgetViewBox.java [hunk 1]
```diff
@@ -63,22 +64,23 @@
...
-                            return;
+                    } else {
+                        for (int i = 0; i < clientObservableList.size(); i++) {
+                            Client client = clientObservableList.get(i);
+                            if (client.isSameClient(displayedClient)) {
+                                displayedClient = client;
+                                displayedClientIndex = i;
+                                return;
+                            }
                         }
```
Comment (qwoprocks) [inline src/main/java/seedu/address/ui/WidgetViewBox.java]: This else block should belong to the other if statement (if (clientObservableList.size() == clientListSize && !c.wasPermutated())), and not the inner one. If not when you remove the client you're currently viewing it won't go back to default view

File: src/main/java/seedu/address/storage/JsonAdaptedNote.java [hunk 2]
```diff
@@ -62,6 +66,20 @@ public boolean isClientNote() {
      * @throws IllegalValueException if there were any data constraints violated in the adapted note.
      */
     public Note toModelType() throws IllegalValueException {
+        if (contents == null) {
+            throw new IllegalValueException(
+                    String.format(MISSING_FIELD_MESSAGE_FORMAT, Note.class.getSimpleName()));
```
Comment (qwoprocks) [inline src/main/java/seedu/address/storage/JsonAdaptedNote.java]: I think this should be 'content' instead of Note.class.getSimpleName(), if not the message will read: Note's Note field is missing

File: src/main/java/seedu/address/storage/JsonAdaptedNote.java [hunk 3]
```diff
@@ -62,6 +66,20 @@ public boolean isClientNote() {
...
+        }
+
+        if (!Note.isValidNote(contents)) {
+            throw new IllegalValueException(Note.MESSAGE_CONSTRAINTS);
+        }
+
+        if (countryCode == null) {
+            throw new IllegalValueException(
+                    String.format(MISSING_FIELD_MESSAGE_FORMAT, Country.class.getSimpleName()));
```
Comment (qwoprocks) [inline src/main/java/seedu/address/storage/JsonAdaptedNote.java]: Should lowercase the getSimpleName so the displayed message will look less weird

**Review by qwoprocks — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/ui/WidgetViewBox.java (hunk 1 above)
Comment (tankangliang) [reply src/main/java/seedu/address/ui/WidgetViewBox.java]: ok changed

File: src/main/java/seedu/address/storage/JsonAdaptedNote.java (hunk 2 above)
Comment (tankangliang) [reply src/main/java/seedu/address/storage/JsonAdaptedNote.java]: done

File: src/main/java/seedu/address/storage/JsonAdaptedNote.java (hunk 3 above)
Comment (tankangliang) [reply src/main/java/seedu/address/storage/JsonAdaptedNote.java]: done

**Review by qwoprocks — APPROVED** [review]
LGTM
