### PR TITLE
Fix code quality in [client, country, note, tag] packages

### LINKED ISSUE #278: Tests for country-related files
- use EP + write EP comment on test cases

### LINKED ISSUE #326: [Model Package] Check code quality
Check package client, country, note, tag

### PR DESCRIPTION
**Pull request by raysonkoh**
## Description

Minor code quality fixes for aforementioned packages.

Fixes #326, Fixes #278 

## Testing

no.

## Remarks

Add any additional remarks for others to take note of.

### CODE REVIEW

File: src/main/java/seedu/address/model/client/Client.java [hunk 1]
```diff
@@ -81,17 +81,23 @@ public LastModifiedInstant getLastModifiedInstant() {
     }
 
     /**
-     * Gets the list of client notes associated with this client.
+     * Gets the unmodifiable list of client notes associated with this client.
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/client/Client.java]:
```suggestion
     * Gets the list of client notes associated with this client as an unmodifiable list.
```

File: src/main/java/seedu/address/model/client/Client.java [hunk 2]
```diff
@@ -81,17 +81,23 @@ public LastModifiedInstant getLastModifiedInstant() {
...
      *
      * @return The list of client notes associated with this client.
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/client/Client.java]:
```suggestion
     * @return An unmodifiable list of client notes associated with this client.
```

File: src/main/java/seedu/address/model/client/Client.java [hunk 3]
```diff
@@ -81,17 +81,23 @@ public LastModifiedInstant getLastModifiedInstant() {
...
      */
     public List<Note> getClientNotesAsUnmodifiableList() {
         return Collections.unmodifiableList(this.clientNotes);
     }
 
+    /**
+     * Gets the list of client notes associated with this client as an Observable List.
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/client/Client.java]:
```suggestion
     * Gets the observable list of client notes associated with this client.
```

File: src/main/java/seedu/address/model/client/Client.java [hunk 4]
```diff
@@ -81,17 +81,23 @@ public LastModifiedInstant getLastModifiedInstant() {
...
+     *
+     * @return The Observable list of client notes associated with this client.
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/client/Client.java]:
```suggestion
     * @return The observable list of client notes associated with this client.
```

File: src/main/java/seedu/address/model/client/UniqueClientList.java [hunk 5]
```diff
@@ -82,6 +82,11 @@ public void remove(Client toRemove) {
         }
     }
 
+    /**
+     * Replaces the contents of this list with all contenst from the given {@code replacement}
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/client/UniqueClientList.java]:
```suggestion
     * Replaces the contents of this list with the contents from the given {@code replacement}.
```

File: src/main/java/seedu/address/model/country/Country.java [hunk 6]
```diff
@@ -3,8 +3,8 @@
 import java.util.Locale;
 
 /**
- * A representation of a Country that can be identified by a 2-letter ISO3166 country-code or by its country
- * name. It contains a list of country notes.
+ * A representation of a Country that is identified by a 2-letter ISO3166 country-code .
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/country/Country.java]:
```suggestion
 * A representation of a Country that is identified by a 2-letter ISO3166 country-code.
```

File: src/main/java/seedu/address/model/country/CountryCodeVerifier.java [hunk 7]
```diff
@@ -3,11 +3,12 @@
...
 
 /**
- * Class that is responsible for verification of ISO3166 country-codes.
+ * The class that is responsible for verification of ISO3166 country-codes.
  */
 public class CountryCodeVerifier {
 
-    public static final String MESSAGE_CONSTRAINTS = "Country code must be a valid 2-letter ISO3166 country code";
+    public static final String MESSAGE_CONSTRAINTS = "Country code must be a valid "
+            + "2-letter ISO3166 country code";
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/country/CountryCodeVerifier.java:11]: Not sure why this message was broken up into two lines

File: src/test/java/seedu/address/logic/parser/CountryNoteAddCommandParserTest.java [hunk 8]
```diff
@@ -23,12 +23,11 @@
     private final CountryNoteAddCommandParser parser = new CountryNoteAddCommandParser(tagNoteMap);
 
     @Test
-    public void parse_noCountryNoNote_throwsParseException() {
+    public void parse() {
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/parser/CountryNoteAddCommandParserTest.java]: If its not too much work, I think it would be better to revert to the previous format of multiple test functions actually, since most of our test files use the multiple function method, and that's what the coding standards seem to recommend also.

File: src/test/java/seedu/address/model/country/CountryNotesManagerTest.java [hunk 9]
```diff
@@ -26,77 +22,58 @@ public void setUp() {
...
 
     @Test
-    public void hasCountryNote_duplicateNote_returnTrue() {
-        for (String countryCode : COUNTRY_CODES) {
-            Country country = new Country(countryCode);
-            CountryNote genericNote = new CountryNote("generic note", country);
-            countryNotesManager.addCountryNote(genericNote);
-            assertTrue(countryNotesManager.hasCountryNote(genericNote));
-        }
+    public void hasCountryNote() {
```
Comment (qwoprocks) [inline src/test/java/seedu/address/model/country/CountryNotesManagerTest.java]: see prev comment

**Review by qwoprocks — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/model/country/CountryCodeVerifier.java (hunk 7 above)
Comment (raysonkoh) [reply src/main/java/seedu/address/model/country/CountryCodeVerifier.java:11]: It will exceed the 120 char limit if its on the same line

File: src/test/java/seedu/address/logic/parser/CountryNoteAddCommandParserTest.java (hunk 8 above)
Comment (raysonkoh) [reply src/test/java/seedu/address/logic/parser/CountryNoteAddCommandParserTest.java]: hmm true. i actually wanted to change all to EP style but its gonna take a lot of time

File: src/main/java/seedu/address/model/note/TagNoteMap.java [hunk 10]
```diff
@@ -102,10 +101,20 @@ public void initTagNoteMapFromCountryNotes(List<Note> countryNotes) {
         return Collections.unmodifiableSet(uniqueTags);
     }
 
+    /** Retrieves all {@code Tag} objects that are associated to a particular {@code Note}.
+     *
+     * @param note The particular {@code Note} to which tags are associated.
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/note/TagNoteMap.java]:
```suggestion
     * @param note The particular {@code Note} to get associated tags for.
```

File: src/main/java/seedu/address/model/note/TagNoteMap.java [hunk 11]
```diff
@@ -102,10 +101,20 @@ public void initTagNoteMapFromCountryNotes(List<Note> countryNotes) {
...
+     * @return Set of {@code Tag} objects that are associated to the note.
+     */
     public Set<Tag> getTagsForNote(Note note) {
         return Collections.unmodifiableSet(noteToTagsMap.getOrDefault(note, new LinkedHashSet<>()));
     }
 
+    /** Retrieves all {@code Note} objects that are associated to a particular {@code Tag}.
+     *
+     * @param tag The particular {@code Tag} to which notes are associated.
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/note/TagNoteMap.java]:
```suggestion
     * @param tag The particular {@code Tag} to get associated notes for.
```

**Review by qwoprocks — APPROVED** [review]
Small comments
