### PR TITLE
Fix code quality for logic package

### LINKED ISSUE #325: [Logic Package] Check code quality

### PR DESCRIPTION
**Pull request by qwoprocks**
## Description

As per title. Also fixed a small bug where `client list` or `client suggest` doesn't change the widget view box back to the default view when in country note view.

Fixes #325

## Testing

NIL

## Remarks

NIL

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ClientEditCommand.java [hunk 1]
```diff
@@ -145,6 +151,9 @@ public boolean equals(Object other) {
         private Timezone timezone;
         private ContractExpiryDate contractExpiryDate;
 
+        /**
+         * Empty constructor.
+         */
```
Comment (rtshkmr) [inline src/main/java/seedu/address/logic/commands/ClientEditCommand.java]: should this be following the same commenting standard? 

"Constructs an EditClientDescriptor. It is an empty constructor that takes in no arguments." or something like that?

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 2]
```diff
@@ -226,7 +226,9 @@ private CommandResult executeCommand(String commandText) throws CommandException
                 widgetPlaceholder.getChildren().add(countryNoteListPanel.getRoot());
             }
 
-            if (commandResult.isResetWidget()) {
+            if (commandResult.shouldResetWidget()) {
+                widgetPlaceholder.getChildren().clear();
+                widgetPlaceholder.getChildren().add(widgetViewBox.getRoot());
```
Comment (qwoprocks) [inline src/main/java/seedu/address/ui/MainWindow.java:231]: Bugfix for when `country note view` is called followed by `client list`, which doesn't reset the widget display viewbox back to default, even though it should.

File: src/main/java/seedu/address/logic/commands/CommandResult.java [hunk 3]
```diff
@@ -56,53 +56,57 @@ public CommandResult(String feedbackToUser) {
...
-
+    /**
+     * Returns true if the help window should be shown to the user.
+     */
     public boolean isShowHelp() {
         return showHelp;
     }
 
+    /**
+     * Returns true if the application should exit.
```
Comment (rtshkmr) [inline src/main/java/seedu/address/logic/commands/CommandResult.java:74]: Would saying something like "Returns true if CommandResult will cause the application to exit" be better? 

tbh the name `isExit` should probably be a little more informative, like `resultIsExit` or `shouldExit()` (to be more in-line with you current comment and standardise with the other `shouldXXX` method names)

File: src/main/java/seedu/address/logic/commands/SuggestCommand.java [hunk 4]
```diff
@@ -14,7 +14,7 @@
 import seedu.address.model.client.SuggestionType;
 
 /**
- * Suggests a list of clients based on the specified suggestion types
+ * Suggests a list of clients based on the specified suggestion types.
```
Comment (rtshkmr) [inline src/main/java/seedu/address/logic/commands/SuggestCommand.java]:
```suggestion
 * Suggests a list of clients based on the specified suggestion type.
```

File: src/main/java/seedu/address/logic/parser/ClientFindCommandParser.java [hunk 5]
```diff
@@ -14,9 +14,10 @@
 public class ClientFindCommandParser implements Parser<ClientFindCommand> {
 
     /**
-     * Parses the given {@code String} of arguments in the context of the ClientFindCommand
-     * and returns a ClientFindCommand object for execution.
-     * @throws ParseException if the user input does not conform the expected format
+     * Parses the given {@code args} in the context of the ClientFindCommand and returns a ClientFindCommand
+     * object for execution.
+     *
+     * @throws ParseException If the user input does not conform the expected format.
```
Comment (rtshkmr) [inline src/main/java/seedu/address/logic/parser/ClientFindCommandParser.java]:
```suggestion
     * @throws ParseException If the user input does not conform to the expected format.
```

File: src/main/java/seedu/address/ui/MainWindow.java (hunk 2 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/ui/MainWindow.java:231]: 👍

**Review by rtshkmr — CHANGES_REQUESTED** [review]
The suggested stuff should probably be reconsidered in the interest of clarity, but other than that almost LGTM.

File: src/main/java/seedu/address/logic/commands/ClientEditCommand.java (hunk 1 above)
Comment (qwoprocks) [reply src/main/java/seedu/address/logic/commands/ClientEditCommand.java]: done

File: src/main/java/seedu/address/logic/commands/CommandResult.java (hunk 3 above)
Comment (qwoprocks) [reply src/main/java/seedu/address/logic/commands/CommandResult.java:74]: I think the reason its called isExit is because the commandresult itself is an exit command. Aka there is only one such command that causes the app to exit. Also,  the "Returns true if CommandResult will cause the application to exit" would be less accurate because the commandresult doesn't cause the application to exit, it just carries the message that the application should exit to the mainwindow class, which then implements the exit

File: src/main/java/seedu/address/logic/commands/SuggestCommand.java (hunk 4 above)
Comment (qwoprocks) [reply src/main/java/seedu/address/logic/commands/SuggestCommand.java]: It should be in the plural because we can have multiple suggestion types being passed in in the form of an ordered set

File: src/main/java/seedu/address/logic/parser/ClientFindCommandParser.java (hunk 5 above)
Comment (qwoprocks) [reply src/main/java/seedu/address/logic/parser/ClientFindCommandParser.java]: good catch, ill change the rest of the parsers as well

File: src/main/java/seedu/address/logic/commands/CommandResult.java (hunk 3 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/logic/commands/CommandResult.java:74]: Alright agreed 👍

File: src/main/java/seedu/address/logic/commands/SuggestCommand.java (hunk 4 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/logic/commands/SuggestCommand.java]: 👍

**Review by rtshkmr — APPROVED** [review]
LGTM
