### PR TITLE
Fixes for dry run comments

### LINKED ISSUE #281: [PE-D] Naming of 'list' command is inconsistent
All commands that deal with clients are prepended with `client`. The `list` command however, is not. This is quite inconvenient as every other command dealing with clients have `client` in front.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ianyong/ped#2

### LINKED ISSUE #304: [PE-D] Standardisation for fields
Consider standardising use of "Expiry: ... " in view function and list function, similar to the other fields.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: rolandyuwy/ped#7

### PR DESCRIPTION
**Pull request by LeeEnHao**
## Description

Fix according to dry run comments.
1. Changes: 
  - list command to client list
  - Fields display for clients now state the fields name

Fixes #304  
Fixes #281 

## Testing

NIL

## Remarks

NIL

### CODE REVIEW

File: src/test/java/seedu/address/logic/parser/CountryNoteDeleteCommandParserTest.java [hunk 1]
```diff
@@ -25,8 +25,8 @@ public void parse_noIndex_throwsParseException() {
     @Test
     public void parse_validIndex_returnsExpected() {
         try {
-            CountryNoteDeleteCommand expected = new CountryNoteDeleteCommand(Index.fromOneBased(1));
-            CountryNoteDeleteCommand actual = parser.parse(" 1");
+            new CountryNoteDeleteCommand(Index.fromOneBased(1));
+            parser.parse(" 1");
         } catch (Exception e) {
             fail();
         }
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/parser/CountryNoteDeleteCommandParserTest.java]: Better to use an assertDoesNotThrow() here

**Review by qwoprocks — APPROVED** [review]
Approved with comments
