### PR TITLE
Client Notes: Fix Indexing Bug

### LINKED ISSUE #152: Add Testing for Delete Client Notes

### LINKED ISSUE #242: Client Note Delete: fix the client note index reference
Currently, `client delete 1 2` will not necessarily delete the second note for client with index 1. This needs to be updated again after the UI for note card is done. 

Ideally, the above method should delete only the 2nd visible client note that is associated to a client, similar to `country note delete`.

### PR DESCRIPTION
**Pull request by rtshkmr**
## Description
With this fix, the client note index passed in for the client note delete command works as expected i.e. `client note delete 2 5` will delete the 2nd client's 5th note. These indices are to be displayed to the user via the UI. Have kept @LeeEnHao informed about this. 

Also found a bug where starting up TBM wasn't updating the tagNoteMap from the existing data. Added relevant call to initialising methods.

Fixes #242 
Fixes #152 

## Testing
- add multiple notes to clients and delete them following the usual command syntax. 

**_Unit Tests currently being added._**

### CODE REVIEW

File: src/main/java/seedu/address/model/client/Client.java [hunk 1]
```diff
@@ -34,7 +36,7 @@
      * Every field must be present and not null.
      */
     public Client(Name name, Phone phone, Email email, Address address, Country country, Timezone timezone,
-            ContractExpiryDate contractExpiryDate, LastModifiedInstant lastModifiedInstant) {
+                  ContractExpiryDate contractExpiryDate, LastModifiedInstant lastModifiedInstant) {
```
Comment (tankangliang) [inline src/main/java/seedu/address/model/client/Client.java]: Is this 8 spaces after the previous line?

File: src/main/java/seedu/address/model/client/Client.java [hunk 2]
```diff
@@ -87,6 +89,15 @@ public LastModifiedInstant getLastModifiedInstant() {
         return Collections.unmodifiableSet(this.clientNotes);
     }
 
+    /**
+     * Gets the list of client notes associated with this client as an observable arraylist.
+     *
+     * @return An Observable List of client notes associated with this client.
```
Comment (tankangliang) [inline src/main/java/seedu/address/model/client/Client.java]: Javadoc here should be unmodifiable? Also, can you change "arraylist" to "ArrayList"?

File: src/test/java/seedu/address/model/client/ClientTest.java [hunk 3]
```diff
@@ -145,4 +151,45 @@ public void hashCode_test() {
...
+        Client client = new ClientBuilder(ALICE).build();
+        Note clientNote = new Note("hell yes");
+        client.addClientNote(clientNote);
+        assertTrue(client.hasClientNote(clientNote));
+        Set<Note> currentNotes = client.getClientNotes();
+        assertThrows(UnsupportedOperationException.class, () -> currentNotes.add(new Note("nice lahh")));
+    }
+
+    @Test
+    public void getClientNotesAsList_modifyUnmodifiableSet_throwsException() {
```
Comment (tankangliang) [inline src/test/java/seedu/address/model/client/ClientTest.java]: Should be unmodifiable list here in the name

File: src/test/java/seedu/address/model/client/ClientTest.java [hunk 4]
```diff
@@ -145,4 +151,45 @@ public void hashCode_test() {
...
+        Client client = new ClientBuilder(ALICE).build();
+        client.addClientNote(new Note("hell yes"));
+        List<Note> currentNotes = client.getClientNotesAsList();
+        assertThrows(UnsupportedOperationException.class, () -> currentNotes.add(new Note("nice lahh")));
+    }
+
+    @Test
+    public void deleteClientNote_deleteExistingNote_doesNotThrowExceptionReturnsTrue() {
```
Comment (tankangliang) [inline src/test/java/seedu/address/model/client/ClientTest.java]: Since nothing is returned here, the name should probably be changed. Maybe `deleteClientNote_validNote_noteIsDeleted`?

File: src/test/java/seedu/address/model/client/ClientTest.java [hunk 5]
```diff
@@ -145,4 +151,45 @@ public void hashCode_test() {
...
+        Note clientNote = new Note("hell yes");
+        client.addClientNote(clientNote);
+        assertTrue(client.hasClientNote(clientNote));
+        assertDoesNotThrow(() -> client.deleteClientNote(clientNote));
+        client.deleteClientNote(clientNote);
+        assertFalse(client.hasClientNote(clientNote));
+    }
+
+    @Test
+    public void toString_positiveTest_returnsTrue() {
```
Comment (tankangliang) [inline src/test/java/seedu/address/model/client/ClientTest.java]: The return true here as well

**Review by tankangliang — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/model/client/Client.java (hunk 1 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/model/client/Client.java]: resolved

File: src/main/java/seedu/address/model/client/Client.java (hunk 2 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/model/client/Client.java]: resolved

File: src/test/java/seedu/address/model/client/ClientTest.java (hunk 3 above)
Comment (rtshkmr) [reply src/test/java/seedu/address/model/client/ClientTest.java]: Resolved

File: src/main/java/seedu/address/logic/commands/ClientNoteDeleteCommand.java [hunk 6]
```diff
@@ -44,21 +44,17 @@ public ClientNoteDeleteCommand(Index targetClientIndex, Index targetClientNoteIn
...
-
         if (targetClientIndex.getZeroBased() >= lastShownClientList.size()) {
             throw new CommandException(Messages.MESSAGE_INVALID_CLIENT_DISPLAYED_INDEX);
         }
-
-        if (targetClientNoteIndex.getZeroBased() >= lastShownClientNoteList.size()) {
+        List<Note> notesList = lastShownClientList.get(targetClientIndex.getZeroBased()).getClientNotesAsList();
+        if (targetClientNoteIndex.getZeroBased() >= notesList.size()) {
             throw new CommandException(MESSAGE_INVALID_CLIENT_NOTE_DISPLAYED_INDEX);
         }
```
Comment (tankangliang) [inline src/main/java/seedu/address/logic/commands/ClientNoteDeleteCommand.java:54]: If the note index is invalid, the message shown is "The client index provided is invalid".

**Review by tankangliang — APPROVED** [review]
LGTM
