### PR TITLE
Client Edit, Client Note Edit Bug Fixes

### LINKED ISSUE #264: Client edit strips the clients of notes
Update createEditedClient and EditClientDescriptor

### LINKED ISSUE #269: clientNoteEdit Tagging Bug: Discarding of Untagged Tag
There was a bug where after creating an untagged client note, if we edit it, the untagged note didn't get removed. 
This has already been fixed, issue creation is for tracking purposes. 

Fix shown: 

1. before: an untagged client note : 
image

2. after: editing that note: 
image

@raysonkoh, keeping you updated here. It's fixed in PR #268

### LINKED ISSUE #272: Bug: Error Display Bug for EditClientNote command
Minor Error Display bug

Demo: 

image

### PR DESCRIPTION
**Pull request by rtshkmr**
## Description

Bug: when editing a non-note field of clients, client note wasn't getting retained. 

Fixes #264 
Fixes #269 
Fixes #272  <== this is a minor display bug

Status: **desired behaviour is reached**.
- Test method: ClientEditCommandTest#execute_changeClientName_preserveExistingClientNotes()

- desired behaviuor is seen in the json file: 
before: 
image

  after command : client edit 1 n/ackerman
  image

## Testing

Ref to example screenshot above

## Remarks

Regression Test Failure was due to the mutability issue again. The following change has been done to `TypicalClients#getTypicalClients`

```
    public static List<Client> getTypicalClients() {
        Client alice = new ClientBuilder(TypicalClients.ALICE).build();
        Client benson = new ClientBuilder(TypicalClients.BENSON).build();
        Client carl = new ClientBuilder(TypicalClients.CARL).build();
        Client daniel = new ClientBuilder(TypicalClients.DANIEL).build();
        Client elle = new ClientBuilder(TypicalClients.ELLE).build();
        Client fiona = new ClientBuilder(TypicalClients.FIONA).build();
        Client george = new ClientBuilder(TypicalClients.GEORGE).build();
        return new ArrayList<>(Arrays.asList(alice, benson, carl, daniel, elle, fiona, george));
    }
```

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/ClientEditCommand.java [hunk 1]
```diff
@@ -86,6 +88,7 @@ public CommandResult execute(Model model) throws CommandException {
 
         model.setClient(clientToEdit, editedClient);
         model.updateFilteredClientList(PREDICATE_SHOW_ALL_CLIENTS);
+        model.initialiseTagNoteMap();
```
Comment (qwoprocks) [inline src/main/java/seedu/address/logic/commands/ClientEditCommand.java]: should this be here?

File: src/main/java/seedu/address/logic/commands/ClientEditCommand.java [hunk 2]
```diff
@@ -105,9 +108,11 @@ private static Client createEditedClient(Client clientToEdit, EditClientDescript
         ContractExpiryDate updatedContractExpiryDate =
                 editClientDescriptor.getContractExpiryDate().orElse(clientToEdit.getContractExpiryDate());
         LastModifiedInstant updatedLastModifiedInstant = new LastModifiedInstant();
-
-        return new Client(updatedName, updatedPhone, updatedEmail, updatedAddress, updatedCountry, updatedTimezone,
-                updatedContractExpiryDate, updatedLastModifiedInstant);
+        LinkedHashSet<Note> retainedClientNotes = new LinkedHashSet<>(clientToEdit.getClientNotes());
+        Client newClient = new Client(updatedName, updatedPhone, updatedEmail, updatedAddress, updatedCountry,
+                updatedTimezone, updatedContractExpiryDate, updatedLastModifiedInstant);
+        retainedClientNotes.stream().forEach(clientNote -> newClient.addClientNote(clientNote));
```
Comment (qwoprocks) [inline src/main/java/seedu/address/logic/commands/ClientEditCommand.java]: don't think the stream() here is needed

File: src/main/java/seedu/address/logic/commands/ClientEditCommand.java [hunk 3]
```diff
@@ -141,6 +146,7 @@ public boolean equals(Object other) {
         private Timezone timezone;
         private ContractExpiryDate contractExpiryDate;
 
+
```
Comment (qwoprocks) [inline src/main/java/seedu/address/logic/commands/ClientEditCommand.java]: extra newline

File: src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java [hunk 4]
```diff
@@ -66,10 +66,10 @@ public CommandResult execute(Model model) throws CommandException {
         accumulatedTags.addAll(newNote.getTags());
         // because parser used tagNoteMap#getUniqueTags, it is okay for there to be duplicates in previous tags and
         // new Note's tags. Overwriting will keep one of the two duplicates, and they are the same object reference.
-        newNote.setTags(accumulatedTags);
-        if (accumulatedTags.size() <= 1 && accumulatedTags.contains(Tag.UNTAGGED)) {
+        if (accumulatedTags.size() > 1 && accumulatedTags.contains(Tag.UNTAGGED)) {
```
Comment (qwoprocks) [inline src/main/java/seedu/address/logic/commands/ClientNoteEditCommand.java]: no need for contains, since set.remove won't throw any errors/exception even if the tag is not inside

File: src/test/java/seedu/address/testutil/TypicalClients.java [hunk 5]
```diff
@@ -88,6 +88,13 @@ public static TbmManager getTypicalTbmManager() {
...
     public static List<Client> getTypicalClients() {
-        return new ArrayList<>(Arrays.asList(ALICE, BENSON, CARL, DANIEL, ELLE, FIONA, GEORGE));
+        Client alice = new ClientBuilder(TypicalClients.ALICE).build();
+        Client benson = new ClientBuilder(TypicalClients.BENSON).build();
+        Client carl = new ClientBuilder(TypicalClients.CARL).build();
+        Client daniel = new ClientBuilder(TypicalClients.DANIEL).build();
+        Client elle = new ClientBuilder(TypicalClients.ELLE).build();
+        Client fiona = new ClientBuilder(TypicalClients.FIONA).build();
+        Client george = new ClientBuilder(TypicalClients.GEORGE).build();
+        return new ArrayList<>(Arrays.asList(alice, benson, carl, daniel, elle, fiona, george));
```
Comment (qwoprocks) [inline src/test/java/seedu/address/testutil/TypicalClients.java]: Can remove TypicalClients.
Also, no need for `new ArrayList` since Arrays.asList already returns a list

File: src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java [hunk 6]
```diff
@@ -155,6 +170,34 @@ public void execute_invalidClientIndexFilteredList_failure() {
...
+        Model expectedModel = new ModelManager(new TbmManager(model.getTbmManager()), new UserPrefs());
+        expectedModel.setClient(lastClient, editedClient);
+        expectedModel.initialiseTagNoteMap();
+        assertCommandSuccess(clientEditCommand, model, expectedMessage, expectedModel);
+        clientEditCommand.execute(model);
+        assertTrue(model.hasClient(editedClient));
+    }
+
+
+
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java]: should only have one newline

File: src/main/java/seedu/address/model/TbmManager.java [hunk 7]
```diff
@@ -23,7 +23,7 @@
 public class TbmManager implements ReadOnlyTbmManager {
 
     private final UniqueClientList clients;
-    private final UniqueTagSet tags;
+    private final UniqueTagSet tags; // todo: deprecate use of UniqueTagSet
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/TbmManager.java]: can't we already remove it? Since its not being used anywhere in the whole codebase

File: src/main/java/seedu/address/logic/parser/ClientNoteEditCommandParser.java [hunk 8]
```diff
@@ -54,7 +54,8 @@ public ClientNoteEditCommand parse(String restOfCommand) throws ParseException {
             newNote.setTags(tags);
             return new ClientNoteEditCommand(targetClientIndex, targetClientNoteIndex, newNote);
         } catch (ParseException pe) {
-            throw new ParseException(MESSAGE_INVALID_COMMAND_FORMAT);
+            throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
+                    ClientNoteEditCommand.MESSAGE_USAGE), pe);
```
Comment (qwoprocks) [inline src/main/java/seedu/address/logic/parser/ClientNoteEditCommandParser.java]: what does the pe do?

File: src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java [hunk 9]
```diff
@@ -33,7 +41,12 @@
  */
 public class ClientEditCommandTest {
 
-    private final Model model = new ModelManager(getTypicalTbmManager(), new UserPrefs());
+    private Model model = new ModelManager(getTypicalTbmManager(), new UserPrefs());
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java]:
```suggestion
    private Model model;
```

Already done in setUp

File: src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java [hunk 10]
```diff
@@ -75,7 +89,7 @@ public void execute_someFieldsSpecifiedUnfilteredList_success() {
 
         Model expectedModel = new ModelManager(new TbmManager(model.getTbmManager()), new UserPrefs());
         expectedModel.setClient(lastClient, editedClient);
-
+        expectedModel.initialiseTagNoteMap();
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java]: If this is needed to be called everytime we create a modelManager, shouldn't we just put it inside the constructor?

File: src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java [hunk 11]
```diff
@@ -104,6 +118,7 @@ public void execute_filteredList_success() {
 
         Model expectedModel = new ModelManager(new TbmManager(model.getTbmManager()), new UserPrefs());
         expectedModel.setClient(model.getSortedFilteredClientList().get(0), editedClient);
+        expectedModel.initialiseTagNoteMap();
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java]: same comment as above

File: src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java [hunk 12]
```diff
@@ -87,7 +101,7 @@ public void execute_noFieldSpecifiedUnfilteredList_success() {
         String expectedMessage = String.format(ClientEditCommand.MESSAGE_EDIT_CLIENT_SUCCESS, editedClient);
 
         Model expectedModel = new ModelManager(new TbmManager(model.getTbmManager()), new UserPrefs());
-
+        expectedModel.initialiseTagNoteMap();
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java]: same comment as above

File: src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java [hunk 13]
```diff
@@ -156,6 +171,34 @@ public void execute_invalidClientIndexFilteredList_failure() {
...
+        ClientBuilder clientInList = new ClientBuilder(lastClient); // rename to currentClient
+        Client editedClient = clientInList.withName(VALID_NAME_BOB).withPhone(VALID_PHONE_BOB).build();
+        editedClient.addClientNote(clientNote);
+        EditClientDescriptor descriptor = new EditClientDescriptorBuilder().withName(VALID_NAME_BOB)
+                .withPhone(VALID_PHONE_BOB).build();
+        ClientEditCommand clientEditCommand = new ClientEditCommand(indexLastClient, descriptor);
+        String expectedMessage = String.format(ClientEditCommand.MESSAGE_EDIT_CLIENT_SUCCESS, editedClient);
+        Model expectedModel = new ModelManager(new TbmManager(model.getTbmManager()), new UserPrefs());
+        expectedModel.setClient(lastClient, editedClient);
+        expectedModel.initialiseTagNoteMap();
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java]: same comment as above

File: src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java [hunk 14]
```diff
@@ -156,6 +171,34 @@ public void execute_invalidClientIndexFilteredList_failure() {
...
+        assertTrue(model.getSortedFilteredClientNotesList().size() == 1);
+        ClientBuilder clientInList = new ClientBuilder(lastClient); // rename to currentClient
+        Client editedClient = clientInList.withName(VALID_NAME_BOB).withPhone(VALID_PHONE_BOB).build();
+        editedClient.addClientNote(clientNote);
+        EditClientDescriptor descriptor = new EditClientDescriptorBuilder().withName(VALID_NAME_BOB)
+                .withPhone(VALID_PHONE_BOB).build();
+        ClientEditCommand clientEditCommand = new ClientEditCommand(indexLastClient, descriptor);
+        String expectedMessage = String.format(ClientEditCommand.MESSAGE_EDIT_CLIENT_SUCCESS, editedClient);
+        Model expectedModel = new ModelManager(new TbmManager(model.getTbmManager()), new UserPrefs());
+        expectedModel.setClient(lastClient, editedClient);
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/commands/ClientEditCommandTest.java:175]: shouldn't setClient method in modelManager also update the tagNoteMap? Not sure where its being done currently.

**Review by qwoprocks — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/parser/ClientNoteEditCommandParser.java (hunk 8 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/logic/parser/ClientNoteEditCommandParser.java]: I reverted to this because as a fix to #272. `pe` is useless here (just needed to keep the Message usage portion, removed it now.

File: src/main/java/seedu/address/logic/commands/ClientEditCommand.java (hunk 2 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/logic/commands/ClientEditCommand.java]: TIL :worried: 

resolved

File: src/test/java/seedu/address/testutil/TypicalClients.java (hunk 5 above)
Comment (rtshkmr) [reply src/test/java/seedu/address/testutil/TypicalClients.java]: Resolved

File: src/main/java/seedu/address/logic/commands/ClientEditCommand.java (hunk 1 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/logic/commands/ClientEditCommand.java]: removed, was unnecessary init. The `setClient` method covers this syncing of the tagNoteMap now

File: src/main/java/seedu/address/model/TbmManager.java (hunk 7 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/model/TbmManager.java]: I'm adding this as a separate issue for an upcoming PR (#273 )so merging these bug fixes can be expedited.

File: src/test/java/seedu/address/testutil/TypicalClients.java [hunk 15]
```diff
@@ -88,14 +87,14 @@ public static TbmManager getTypicalTbmManager() {
...
-        Client george = new ClientBuilder(TypicalClients.GEORGE).build();
-        return new ArrayList<>(Arrays.asList(alice, benson, carl, daniel, elle, fiona, george));
+        Client alice = new ClientBuilder(ALICE).build();
+        Client benson = new ClientBuilder(BENSON).build();
+        Client carl = new ClientBuilder(CARL).build();
+        Client daniel = new ClientBuilder(DANIEL).build();
+        Client elle = new ClientBuilder(ELLE).build();
+        Client fiona = new ClientBuilder(FIONA).build();
+        Client george = new ClientBuilder(GEORGE).build();
+        return (Arrays.asList(alice, benson, carl, daniel, elle, fiona, george));
```
Comment (qwoprocks) [inline src/test/java/seedu/address/testutil/TypicalClients.java]:
```suggestion
        return Arrays.asList(alice, benson, carl, daniel, elle, fiona, george);
```

No need for extra brackets

File: src/main/java/seedu/address/model/ModelManager.java [hunk 16]
```diff
@@ -147,6 +148,7 @@ public void addClient(Client client) {
     public void setClient(Client target, Client editedClient) {
         requireAllNonNull(target, editedClient);
         tbmManager.setClient(target, editedClient);
+        initialiseTagNoteMap();
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/ModelManager.java:154]: is there anything we can do in tagnotemap that would allow us to replace a client instead of doing re-init?

**Review by qwoprocks — CHANGES_REQUESTED** [review]

File: src/test/java/seedu/address/testutil/TypicalClients.java (hunk 15 above)
Comment (rtshkmr) [reply src/test/java/seedu/address/testutil/TypicalClients.java]: No idea how you're so attentive :goat:

**Review by qwoprocks — APPROVED** [review]
