### PR TITLE
Fix Ordering Bug for ClientNoteEdit

### LINKED ISSUE #270: Notes do not follow the same order always
Current collections for Tags and Notes includes the use of `Set` class. To be refactored to use `LinkedHashSet` wherever possible to preserve insertion order. 
This does not affect the feature's expected operations hence shall not be tagged as a bug and priority will be set to Medium.

### LINKED ISSUE #296: [PE-D] Edit Client Note will change order of notes after editing
The order of client notes is not preserved when notes are edited.

Initial adding of 2 notes to Bernice:

Command to edit first note "test" to "test3"

After edit command. "test3" is after "test2" even though it should be before the latter.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: khoongwk/ped#4

### PR DESCRIPTION
**Pull request by rtshkmr**
## Description

Changed notes from being part of Sets to being part of lists.
The note kept getting popped to the bottom of the list because editing used to be implemented as a removal of a target note  and an insertion of its edited form. 

Also added the test `ClientNoteEditCommandTest#execute_editExistingUntaggedNoteToAddTag_discardsDefaultUntaggedTag()` and found a flaw in TagNoteMap initialisation and fixed that.

GUI has been updated too.

Fixes #270 Fixes #296 

## Testing

NIL

## Remarks

NIL

### CODE REVIEW

File: src/main/java/seedu/address/model/note/TagNoteMap.java [hunk 1]
```diff
@@ -28,18 +30,19 @@
...
+    private final LinkedHashSet<Note> noteSet = new LinkedHashSet<>(); // TODO: not really needed
+    private final Map<Tag, List<Note>> tagToNotesMap = new HashMap<>();
+    private final Map<Note, LinkedHashSet<Tag>> noteToTagsMap = new HashMap<>(); // TODO: not really needed
 
     /**
      * Constructor ensures our unique tag map has the UNTAGGED tag.
      */
     public TagNoteMap() {
         uniqueTagMap.put(Tag.UNTAGGED, Tag.UNTAGGED);
+        tagToNotesMap.put(Tag.UNTAGGED, new ArrayList<>());
```
Comment (rtshkmr) [inline src/main/java/seedu/address/model/note/TagNoteMap.java:42]: took a while to find this 😞

File: src/main/java/seedu/address/model/client/Client.java [hunk 2]
```diff
@@ -87,8 +85,8 @@ public LastModifiedInstant getLastModifiedInstant() {
      *
      * @return The list of client notes associated with this client.
      */
-    public Set<Note> getClientNotes() {
-        return Collections.unmodifiableSet(this.clientNotes);
+    public List<Note> getClientNotes() {
+        return Collections.unmodifiableList(this.clientNotes);
     }
```
Comment (LeeEnHao) [inline src/main/java/seedu/address/model/client/Client.java]: This could be a duplicated method of the getClientNotesAsList

File: src/main/java/seedu/address/model/client/Client.java [hunk 3]
```diff
@@ -131,9 +136,9 @@ public void deleteClientNote(Note clientNote) {
      */
     public void editClientNote(Note clientNote, Note newNote) {
         requireNonNull(clientNote);
-        this.clientNotes.remove(clientNote);
-        this.clientNotes.add(newNote);
-        // todo: keep existing tags.
+        int targetIdx = clientNotes.indexOf(clientNote);
+        clientNotes.set(targetIdx, newNote);
+        assert(!clientNotes.contains(clientNote));
```
Comment (qwoprocks) [inline src/main/java/seedu/address/model/client/Client.java]:
```suggestion
        assert !clientNotes.contains(clientNote);
```
For standardization

File: src/main/java/seedu/address/model/client/Client.java (hunk 2 above)
Comment (qwoprocks) [reply src/main/java/seedu/address/model/client/Client.java]: Would suggest changing this method name to `getClientNotesAsUnmodifiableList()`

File: src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java [hunk 4]
```diff
@@ -53,22 +53,53 @@ public void execute_validClientIdxValidNoteIdx_generatesClientNoteEditCommandSuc
         ClientNoteEditCommand clientNoteEditCommand = new ClientNoteEditCommand(clientIdx, clientNoteIdx, newEditNote);
         assertCommandSuccess(clientNoteEditCommand, model, expectedResult, expectedModel);
     }
+    // test to show untagged tag removal (in future commit) behaviour is already verified by json file
```
Comment (qwoprocks) [inline src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java]: Needs a new line before this comment. Also, I'm not too sure what this comment means?

**Review by qwoprocks — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/model/client/Client.java (hunk 2 above)
Comment (rtshkmr) [reply src/main/java/seedu/address/model/client/Client.java]: changed to `getClientNotesAsUnmodifiableList()`

Comment (rtshkmr) [reply src/main/java/seedu/address/model/client/Client.java]: also deprecated the `getClientNotesAsList`

File: src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java (hunk 4 above)
Comment (rtshkmr) [reply src/test/java/seedu/address/logic/commands/ClientNoteEditCommandTest.java]: Removed the comment because the test name is descriptive enough

**Review by qwoprocks — APPROVED** [review]
LGTM, but is it possible to also add in a more informative message for client note edit? Using String.format to show the user which client, the original note content, and the new note content. Can do in a separate PR if you want but imo its a simple enough change to do in this one.

**Comment by rtshkmr** [comment]
@qwoprocks  Merged after doing this: 🏃‍♂️ 

> LGTM, but is it possible to also add in a more informative message for client note edit? Using String.format to show the user > which client, the original note content, and the new note content. Can do in a separate PR if you want but imo its a simple enough change to do in this one.

image
